### ISSUE TITLE
TASK Improve statistics

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#136]
Include the total sum of invoices sent in the statistics.

Also change the 25 years back to the amount of years since 2007. While we're been serving some of our customers since 1999, the company was founded 2007.

### Subtasks

* [x] Change 25 years back to the amount of years since 2007
* [x] Fixed some route SEO titles and decriptions to use their own translation tags
* [x] Add sent invoice sums
* [ ] Improved max width of the index page image
