### ISSUE TITLE
TASK Add bookkeeping database tables - part 1

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#144]
### Subtasks

* [x] Table for purchase invoice debit mapping
* [x] Table for bookkeeping categories
* [x] Table for bookkeeping accounts
