### ISSUE TITLE
TASK Add bookkeeping database tables - part 2

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#156]
### Goal

TODO

### Subtasks

* [ ] Table for purchase invoice credit mapping
* [ ] Table for invoice debit mapping
* [ ] Table for invoice credit mapping
