### ISSUE TITLE
Add support to post on Facebook to Sendanor Agent CLI

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#165]
### Goal

Add support to post to Facebook into our Agent CLI. Use our [Facebook client](https://github.com/hyperifyio/io.hyperify.core/issues/14).

### Complete sequence diagram

```mermaid
sequenceDiagram

    box Green Frontend
        participant Alice
        participant Browser
        participant CLI
    end

    box The Goal
        participant Library
    end

    box Backend
        participant GraphAPI
    end

    Alice->>CLI: Start login

    CLI->>Library: Get authentication URL with these permissions
    Library-->>CLI: Here's https://www.facebook.com/dialog/oauth

    CLI-->>Alice: Go to https://www.facebook.com/dialog/oauth

    Alice->>Browser: Opens up https://www.facebook.com/dialog/oauth
    Alice-->>Browser: Follows up on instructions to authenticate
    Browser-->>Alice: All ready, you can close the window

    Library-->>CLI: All set! Here's code.

    CLI->>Library: Here's my code, give me user access token

    Library->>GraphAPI: Here's my code, give me user access token
    GraphAPI-->>Library: Here's user access token

    Library-->>CLI: Here's user access token

    CLI->>Library: Here's user access token, give me list of pages with page access tokens

    Library->>GraphAPI: Here's my user access token, give me list of pages with accounts (pages) with access tokens
    GraphAPI-->>Library: Here's list of accounts (pages)
    Library-->>CLI: Here's list of accounts (pages) with access tokens

    CLI-->>Alice: Here's the page access token

    Alice->>CLI: Here's the page access token, post on my feed.

    CLI->>Library: Here's page access token, post on this feed
    Library->>GraphAPI: Here's page access token, post on this feed.
    GraphAPI-->>Library: Posted!
    Library-->>CLI: Posted!

    CLI-->>Alice: Post ready!

```

### Subtasks

* [x] Implement `agent facebook login`
* [x] Implement frontend page where Facebook will redirect
* [x] Implement `agent facebook submit-code`
* [x] Implement `agent facebook accounts`
* [x] Implement `agent facebook post`
