### ISSUE TITLE
TASK Send email when a product is purchased

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#172]
### Goal

We need to send an email with a link to the inventory item when a new inventory item is added.

For example, when a user purchases a shell account, it should send an email message about it using a link like `https://www.sendanor.fi/my/clients/:clientId/inventory/:inventoryitemId`. 

### TODO

* [ ] Send an email message when new inventory items are added (this must be done on the backend side)
* [ ] Include a link to the inventory item
* [ ] Add a text using the translation tag. The message should mention that there might be additional product specific settings to configure (e.g. user name).
* [ ] Optionally send it only after the invoice has been paid
* [ ] Optionally make it configurable which products generate these messages
