### ISSUE TITLE
TASK Improved automated posts and ads on Facebook

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#174]
### Goal

We want to automate our social media advertising. To do that, we could create a microservice which would create dynamic posts about our services to our social media channels, and enable ads with UTM parameters.

Later we could optimize this so that it could learn and optimize to use ads which produce good results based on the data from UTM parameters.

The microservice which uses Facebook API can also be written in Golang.

Initial work done at #162

### Subtasks

* [ ] Set up a Facebook sandbox environment
* [ ] #163
* [ ] Dynamic service which can create smart posts from our product catalog, possibly using ChatGPT, and save them to the database for later use
* [ ] Integrate database to collect statistics about how effective the ad was using UTM parameters
