### ISSUE TITLE
TASK Production database clean up

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#210]
### Goal

Our production database is missing quite a lot of information currently, which is a blocker for improving our online service.

### Subtasks

* [x] Make sure each payment record has a unique and specific description name
    * [x] Fix missing slash from lines starting with `Nimipalvelu ...`
    * [x] Fix lines with`Shell-tunnus ...` to have initial `Shelli /`
    * [x] Fix lines with`Nimipalvelu verkkotunnukselle ...` to have initial `Nimipalvelu /`
    * [x] Fix `Verkkotunnuksen rekisteröintimaksu /` to `Verkkotunnus / `
    * [x] Fix missing slash from lines with`Nimipalvelu ...` to have initial `Nimipalvelu /`
    * [x] Fix missing slash from lines with`Verkkotunnus ...` to have initial `Verkkotunnus /`
    * [x] Fix missing slash from lines with`Virtuaalipalvelin ...` to have initial `Virtuaalipalvelin /`
    * [x] Fix `Domain registeration fee /` to start with `Verkkotunnus /`
    * [x] Starting with `Nimipalvelu /`
    * [x] Starting with `Sähköposti /`
    * [x] Starting with `Shelli /`
    * [x] Starting with `Verkkotunnuksen lisäpalvelu /`
    * [x] Starting with `Verkkotunnus /`
    * [x] Starting with `Virtuaalipalvelimen lisäpalvelu /`
    * [x] Starting with `Virtuaalipalvelin /`
    * [x] Starting with `Webhotelli /`
    * [x] Starting with `Webhotellin lisäpalvelu /`
    * [x] Starting with `Yrityspalvelut /`
* [ ] Verify each inventory item in the database is linked to a payment record
* [ ] Verify each payment record in the database is linked into inventory item
* [ ] Verify there is no payment records without an inventory record
* [ ] Verify each payment record has a link to correct product records

### Queries

Look payment records for `Shelli /*`:

```mysql
SELECT payment_id, description, client_id, inventory_item_id, is_recurring, is_terminated, on_hold, billing_period FROM sendanor_payment WHERE is_recurring=1 AND is_terminated=0 AND description LIKE 'Shelli / %' ORDER BY description;
```
