### ISSUE TITLE
TASK Improve products

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#251]
### Tasks

* [x] Email product specs added
* [x] Email product included in the webhotel?
* [x] Database specs added to web product specs
