### ISSUE TITLE
BUG Some SVG images have incorrect attributes

### ISSUE THREAD

**Issue by thejhh** [sendanor/project-sendanor.fi#57]
### Description

We had some SVG images which have `id` and `class` attributes. These are not compatible with ReactComponent use case.

### Subtasks

* [ ] ./fi/sendanor/frontend/assets/paytrail/mobilepay.svg
* [ ] ./fi/sendanor/frontend/assets/icons/wp.svg
* [ ] ./fi/sendanor/frontend/assets/logos/discord-brands.svg
* [ ] ./fi/sendanor/frontend/assets/logos/palvelinkauppa.svg
* [ ] ./fi/sendanor/frontend/assets/logos/linkedin-brands.svg
* [ ] ./fi/sendanor/frontend/assets/logos/github-brands.svg
* [ ] ./fi/sendanor/frontend/assets/logos/facebook-brands.svg
* [ ] ./fi/sendanor/frontend/assets/logos/twitter-brands.svg
